version: "3"

volumes:
  database:
    driver: local

services:
  mysql:
    platform: linux/amd64
    image: mysql:8.0.28
    container_name: trello_analysis_mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: trello_analysis
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - database:/var/lib/mysql
  phpmyadmin:
    image:
      phpmyadmin/phpmyadmin:latest
    container_name: trello_analysis_phpmyadmin
    links:
      - mysql:db
    ports:
      - "8002:80"

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.1.0/24
